# Generated by Django 4.2.17 on 2025-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
